name: API test with rest assured in PowerShell 
on: push

jobs:
  api-test-job:
    name: rest assured in pwsh
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run the API-test in pwsh
        shell: pwsh
        run: |
          mvn clean test 
  build-with-Maven:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
      - name: run API test in maven 
        run: mvn -B clean test --file pom.xml

 
