name: API test with rest assured in PowerShell 
on: push

jobs:
  api-test-job:
    name: rest assured
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run the API-test in pwsh
        shell: pwsh
        run: |
          mvn clean test

 
